# Generated by Django 5.2 on 2025-08-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_categoriaproducto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perecedero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='sku-temp', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
