# Generated by Django 5.2 on 2025-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_producto_imagen_producto_perecedero_producto_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
