# Generated by Django 5.2 on 2025-09-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_categoriaproducto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
