# Generated by Django 5.2 on 2025-10-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_producto_fecha_caducidad'),
        ('empresas', '0005_empresa_smtp_host_empresa_smtp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
