# Generated by Django 5.2 on 2025-10-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_categoriaproducto_empresa_producto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='atributos_personalizados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
