# Generated by Django 5.2 on 2025-04-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('costo_por_persona', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen_principal', models.ImageField(upload_to='servicios/')),
                ('galeria', models.ManyToManyField(blank=True, to='servicios.imagenservicio')),
            ],
        ),
    ]
