# Generated by Django 5.2 on 2025-04-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='titulo',
            new_name='tituloo',
        ),
    ]
