# Generated by Django 5.2 on 2025-04-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_servicio_duracion_servicio_restricciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='servicio',
        ),
    ]
