# Generated by Django 5.2 on 2025-04-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_remove_servicio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subservicios', to='servicios.tiposervicio'),
            preserve_default=False,
        ),
    ]
