# Generated by Django 5.2 on 2025-04-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_servicio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='costo_con_descuento',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='costo_niño',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
    ]
