# Generated by Django 5.2 on 2025-05-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_remove_tiposervicio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervicio',
            name='descripcion',
        ),
    ]
