# Generated by Django 5.2 on 2025-05-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_remove_tiposervicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
