# Generated by Django 5.2 on 2025-05-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_activa'),
        ('servicios', '0013_tiposervicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
