# Generated by Django 5.2 on 2025-11-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_servicio_empresa'),
    ]

    operations = [
    ]
