# Generated by Django 5.2 on 2025-06-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_alter_servicio_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('porDia', 'Por día'), ('porHora', 'Por hora')], default=2, max_length=15),
            preserve_default=False,
        ),
    ]
