# Generated by Django 5.2 on 2025-06-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_remove_servicio_estado_tiposervicio_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='estado',
            new_name='tipo',
        ),
    ]
