# Generated by Django 5.2 on 2025-09-09 06:24

import django.db.models.deletion
import servicios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0018_rename_estado_tiposervicio_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenservicio',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='galeria',
        ),
        migrations.AddField(
            model_name='imagenservicio',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden en la galería (0 arriba).'),
        ),
        migrations.AddField(
            model_name='imagenservicio',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenservicio',
            name='imagen',
            field=models.ImageField(upload_to=servicios.models.upload_to_service_gallery),
        ),
    ]
