# Generated by Django 5.2 on 2025-09-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_alter_imagenservicio_options_remove_servicio_galeria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenservicio',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden en la galería (0 arriba).'),
        ),
    ]
