# Generated by Django 5.2 on 2025-10-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_imagenservicio_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='atributos_personalizados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
