# Generated by Django 5.2 on 2025-10-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_imagenservicio_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenservicio',
            name='empresa',
        ),
    ]
