# Generated by Django 5.2 on 2025-10-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0022_servicio_atributos_personalizados'),
    ]

    operations = [
        # Primero agregar el campo permitiendo NULL
        migrations.AddField(
            model_name='imagenservicio',
            name='servicio',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='imagenes',
                to='servicios.servicio'
            ),
        ),
        # Luego eliminar las imágenes huérfanas sin servicio asignado
        migrations.RunSQL(
            sql="DELETE FROM servicios_imagenservicio WHERE servicio_id IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Finalmente hacer el campo obligatorio (NOT NULL)
        migrations.AlterField(
            model_name='imagenservicio',
            name='servicio',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='imagenes',
                to='servicios.servicio'
            ),
        ),
    ]
