# Generated by Django 5.2 on 2025-10-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('servicios', '0023_add_servicio_to_imagenservicio'),
    ]

    operations = [
        # Paso 1: Agregar el campo permitiendo NULL temporalmente
        migrations.AddField(
            model_name='tiposervicio',
            name='empresa',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='empresas.empresa'
            ),
        ),
        
        # Paso 2: Asignar todos los tipos de servicio existentes a Xoletongo (ID=1)
        migrations.RunSQL(
            sql="UPDATE servicios_tiposervicio SET empresa_id = 1 WHERE empresa_id IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        
        # Paso 3: Hacer el campo obligatorio (NOT NULL)
        migrations.AlterField(
            model_name='tiposervicio',
            name='empresa',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='empresas.empresa'
            ),
        ),
    ]
