# Generated by Django 5.2 on 2025-10-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0024_add_empresa_to_tiposervicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenservicio',
            name='empresa',
        ),
    ]
