# Generated by Django 5.2 on 2025-05-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_activa'),
        ('usuarios', '0002_customuser_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
