# Generated by Django 5.2 on 2025-06-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Empleado', 'Empleado'), ('Encargado', 'Encargado'), ('Cliente', 'Cliente')], default='Cliente', max_length=20),
        ),
    ]
