# Generated by Django 5.2 on 2025-10-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devpanel', '0003_alter_seccion_tipo_rol'),
        ('usuarios', '0005_customuser_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
        migrations.AddField(
            model_name='customuser',
            name='atributos_personalizados',
            field=models.JSONField(blank=True, default=dict, help_text='Valores de los atributos personalizados según el rol asignado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol_legacy',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Empleado', 'Empleado'), ('Encargado', 'Encargado'), ('Cliente', 'Cliente')], db_column='rol', default='Cliente', help_text="DEPRECADO: usar campo 'rol' en su lugar", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol_nuevo',
            field=models.ForeignKey(blank=True, db_column='rol_id', help_text='Rol del usuario con atributos personalizados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='devpanel.rol'),
        ),
    ]
