# Generated by Django 5.2 on 2025-04-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen_principal', models.ImageField(upload_to='hospedajes/')),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de personas')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedajes', to='reservaciones.tipohospedaje')),
            ],
        ),
    ]
