# Generated by Django 5.2 on 2025-05-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='pago_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
