# Generated by Django 5.2 on 2025-04-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_reservacion_reservacion_servicio_delete_hospedaje_and_more'),
        ('servicios', '0009_servicio_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion_servicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoServicio', to='servicios.servicio'),
        ),
    ]
