# Generated by Django 5.2 on 2025-05-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_reservacion_pago_realizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='numero_personas',
            new_name='numero_adultos',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='numero_descuento',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacion',
            name='numero_ninos',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
