# Generated by Django 5.2 on 2025-04-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_alter_reservacion_servicio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='pago_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
