# Generated by Django 5.2 on 2025-05-05 05:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_rename_numero_personas_reservacion_numero_adultos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
