# Generated by Django 5.2 on 2025-05-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0004_reservacion_total_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=15),
        ),
    ]
