# Generated by Django 5.2 on 2025-05-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0004_reservacion_total_pagado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name_plural': 'Reservaciones'},
        ),
    ]
