# Generated by Django 5.2 on 2025-05-09 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0005_reservacion_estado'),
        ('servicios', '0013_tiposervicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion_servicio',
            name='id_reservacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_reservado', to='reservaciones.reservacion'),
        ),
        migrations.AlterField(
            model_name='reservacion_servicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_servicio', to='servicios.servicio'),
        ),
    ]
