# Generated by Django 5.2 on 2025-05-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0005_alter_reservacion_options'),
        ('reservaciones', '0006_alter_reservacion_servicio_id_reservacion_and_more'),
    ]

    operations = [
    ]
