# Generated by Django 5.2 on 2025-05-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_activa'),
        ('reservaciones', '0008_alter_reservacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
