# Generated by Django 5.2 on 2025-05-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_activa'),
        ('reservaciones', '0010_alter_reservacion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
