# Generated by Django 5.2 on 2025-06-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0012_reservacion_hora_recepcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='hora_recepcion',
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
