# Generated by Django 5.2 on 2025-06-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0013_remove_reservacion_hora_recepcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='hora_recepcion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
