# Generated by Django 5.2 on 2025-11-06 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_empresa_servicios_habilitado'),
        ('reservaciones', '0014_reservacion_hora_recepcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
