# Generated by Django 5.2 on 2025-06-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0014_reservacion_hora_recepcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name_plural': 'Reservaciones'},
        ),
    ]
