# Generated by Django 5.2 on 2025-10-14 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_smtp_host_empresa_smtp_password_and_more'),
        ('reservaciones', '0015_alter_reservacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion_servicio',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
