# Generated by Django 5.2 on 2025-10-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0016_reservacion_servicio_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion_servicio',
            name='empresa',
        ),
    ]
