# Generated by Django 5.2 on 2025-10-24 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0011_empresa_servicios_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(default=dict, help_text='Datos del formulario de contacto (nombre, email, mensaje, etc.)')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False, help_text='Marca si el mensaje fue leído')),
                ('respondido', models.BooleanField(default=False, help_text='Marca si el mensaje fue respondido')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas del staff')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_contacto', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
