# Generated by Django 5.2 on 2025-10-17 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0006_empresa_creado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(choices=[('Producto', 'Producto'), ('Servicio', 'Servicio')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('attribute_type', models.CharField(choices=[('TEXT', 'Texto Corto'), ('TEXTAREA', 'Texto Largo'), ('NUMBER', 'Número'), ('DATE', 'Fecha'), ('BOOLEAN', 'Sí/No (Checkbox)')], max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'target_model', 'name')},
            },
        ),
    ]
