# Generated by Django 5.2 on 2025-10-21 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devpanel', '0001_initial'),
        ('empresas', '0007_tema_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('home', 'Inicio'), ('servicios', 'Servicios'), ('productos', 'Productos'), ('nosotros', 'Nosotros'), ('galeria', 'Galería'), ('contacto', 'Contacto')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['slug'],
                'unique_together': {('empresa', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hero', 'Hero (Banner Principal)'), ('texto', 'Bloque de Texto'), ('carousel', 'Carrusel de Imágenes'), ('galeria', 'Galería de Imágenes'), ('features', 'Características/Beneficios'), ('cta', 'Call to Action'), ('testimonios', 'Testimonios'), ('mapa', 'Mapa')], max_length=50)),
                ('titulo', models.CharField(blank=True, help_text='Título interno para identificar la sección', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número = más arriba)')),
                ('activa', models.BooleanField(default=True)),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración específica de la sección (título, subtítulo, imágenes, etc.)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='devpanel.pagina')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden', 'creado_en'],
            },
        ),
    ]
