# Generated by Django 5.2 on 2025-10-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devpanel', '0002_add_pagina_seccion_models'),
        ('empresas', '0007_tema_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='tipo',
            field=models.CharField(choices=[('hero', 'Hero (Banner Principal)'), ('texto', 'Bloque de Texto'), ('carousel', 'Carrusel de Imágenes'), ('galeria', 'Galería de Imágenes'), ('features', 'Características/Beneficios'), ('cta', 'Call to Action'), ('testimonios', 'Testimonios'), ('mapa', 'Mapa'), ('instagram', 'Instagram Feed'), ('contacto_form', 'Formulario de Contacto'), ('servicios_accordion', 'Tarjetas de Servicios')], max_length=50),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del rol (ej: Guía Turístico)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de las responsabilidades del rol')),
                ('atributos_schema', models.JSONField(blank=True, default=list, help_text='Definición de atributos personalizados para usuarios con este rol')),
                ('permisos', models.JSONField(blank=True, default=dict, help_text='Permisos específicos del rol (para expansión futura)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este rol está activo y puede ser asignado a usuarios')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este rol', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['empresa', 'nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
