# Generated by Django 5.2 on 2025-10-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devpanel', '0003_alter_seccion_tipo_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.CharField(choices=[('home', 'Inicio'), ('servicios', 'Servicios'), ('productos', 'Productos'), ('nosotros', 'Nosotros'), ('galeria', 'Galería'), ('contacto', 'Contacto'), ('footer', 'Footer')], max_length=50),
        ),
    ]
