# Generated by Django 5.2 on 2025-05-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=255)),
                ('cuenta_bancaria', models.CharField(max_length=100)),
                ('clabe', models.CharField(max_length=18)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
