# Generated by Django 5.2 on 2025-05-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
