# Generated by Django 5.2 on 2025-05-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='numero_terjeta',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(max_length=18),
        ),
    ]
