# Generated by Django 5.2 on 2025-05-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_numero_terjeta_alter_empresa_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_titular',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
