# Generated by Django 5.2 on 2025-06-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_nombre_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='Servidor SMTP (p. ej. smtp.gmail.com)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Contraseña SMTP (o contraseña de aplicación)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='Puerto SMTP (p. ej. 587 para TLS, 465 para SSL)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Activar SSL al enviar correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Activar TLS al enviar correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_user',
            field=models.CharField(blank=True, help_text='Usuario SMTP (p. ej. nombre@dominio.com)', max_length=100, null=True),
        ),
    ]
