# Generated by Django 5.2 on 2025-10-16 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_smtp_host_empresa_smtp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 16, 5, 10, 17, 557666, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
