# Generated by Django 5.2 on 2025-10-20 03:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_creado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del tema (ej: 'Moderno', 'Clásico')", max_length=100, unique=True)),
                ('color_primario', models.CharField(default='#4CAF50', help_text='Color principal del tema (hexadecimal)', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido (ej: #4CAF50)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_secundario', models.CharField(default='#2196F3', help_text='Color secundario del tema', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_acento', models.CharField(default='#FF9800', help_text='Color de acento para botones y enlaces', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_texto', models.CharField(default='#333333', help_text='Color del texto principal', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido', regex='^#[0-9A-Fa-f]{6}$')])),
                ('color_fondo', models.CharField(default='#FFFFFF', help_text='Color de fondo principal', max_length=7, validators=[django.core.validators.RegexValidator(message='Debe ser un color hexadecimal válido', regex='^#[0-9A-Fa-f]{6}$')])),
                ('fuente_principal', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Georgia', 'Georgia'), ('Times New Roman', 'Times New Roman')], default='Roboto', max_length=50)),
                ('fuente_secundaria', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Georgia', 'Georgia'), ('Times New Roman', 'Times New Roman')], default='Open Sans', max_length=50)),
                ('estilo_layout', models.CharField(choices=[('moderno', 'Moderno'), ('clasico', 'Clásico'), ('minimalista', 'Minimalista'), ('corporativo', 'Corporativo')], default='moderno', max_length=20)),
                ('logo_header', models.ImageField(blank=True, help_text='Logo para el header', null=True, upload_to='temas/logos/')),
                ('imagen_hero', models.ImageField(blank=True, help_text='Imagen principal del home', null=True, upload_to='temas/hero/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='temas/favicons/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='dominio_personalizado',
            field=models.CharField(blank=True, help_text="Dominio propio de la empresa (ej: 'www.xoletongo.com')", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subdominio',
            field=models.SlugField(blank=True, help_text="Subdominio para acceder al sitio (ej: 'xoletongo' para xoletongo.midominio.com)", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=False, help_text='Empresa actualmente activa en el sistema'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tema',
            field=models.ForeignKey(blank=True, help_text='Tema visual para el sitio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='empresas.tema'),
        ),
    ]
