# Generated by Django 5.2 on 2025-10-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_tema_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='navbar_estilo',
            field=models.CharField(choices=[('transparente_scroll', 'Transparente con scroll'), ('color_primario', 'Siempre color primario'), ('negro', 'Siempre negro')], default='color_primario', help_text='Estilo de la barra de navegación', max_length=30),
        ),
    ]
