# Generated by Django 5.2 on 2025-10-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_tema_navbar_estilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='productos_habilitado',
            field=models.BooleanField(default=False, help_text='Habilitar tienda/catálogo de productos para esta empresa'),
        ),
    ]
