# Generated by Django 5.2 on 2025-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_empresa_productos_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='resenas_habilitado',
            field=models.BooleanField(default=True, help_text='Habilitar sistema de reseñas para productos y servicios'),
        ),
    ]
