# Generated by Django 5.2 on 2025-10-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_empresa_resenas_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='servicios_habilitado',
            field=models.BooleanField(default=True, help_text='Habilitar visualización y gestión de servicios'),
        ),
    ]
